export interface ReservationMiscViewDataFull {
	miscChargeId: number;
	miscChargeCode: number;
	unit: number;
	name: string;
	description: string;
	calculationType: "Fixed" | "Perday";
	taxNotAvailable: boolean;
	isCommission: boolean;
	value: number;
	totalValue: number;
	startDate: string;
	endDate: string;
	quantity: number;
	createdDate: string | null;
	gLcode: string | null;
	locationMiscChargeId: number;
	isChargeByPeriod: boolean;
	isTaxable: boolean;
	locationTaxIds: string | null;
	isSelected: boolean;
	isQuantity: boolean;
	locationMiscChargeID: number;
	vehicleTypeId: number;
	miscChargeID: number;
	misChargeCode: number;
	isOptional: boolean;
	printValue: number | null;
	oldStartDateString: string | null;
	oldEndDateString: string | null;
	startDateString: string | null;
	createddateString: string | null;
	endDateString: string | null;
	isDeleted: boolean;
	isFreeze: boolean;
	isAlreadySelected: boolean;
	isDeductible: boolean;
	locationId: number;
	locationName: string | null;
	vehicleType: number | null;
	miscTaxList: string | null;
	totaltax: number;
	subTotal: number;
	amountPaid: number | null;
	amountRemaining: number | null;
	miscchargeTypeId: number;
	option: number;
	misChargeOptionList: string | null;
	optionId: number | null;
}
export interface ReservationViewDataFull {
	reservationview: {
		reserveId: number;
		additionalCharge: number;
		reservationNumber: string | null;
		reservationType: string | null;
		owningLocationId: number;
		lowestRate: null;
		clientId: number;
		customerId: number;
		vehicleId: number;
		vehicleMakeName: string | null;
		trim: string | null;
		year: number;
		startDate: string;
		endDate: string;
		createdDate: string | null;
		notes: string | null;
		licenseNo: string | null;
		vehicleNo: string | null;
		fuelType: string | null;
		fuelLevel: string | null;
		transmission: string | null;
		currentOdometer: number;
		color: string | null;
		doors: number | null;
		vin: string | null;
		statusId: number;
		insuranceAmt: number | null;
		startLocationId: number;
		startLocationName: string | null;
		startLocationAddress1: string | null;
		startLocationAddress2: string | null;
		startLocationCity: string | null;
		startLocationPhone: string | null;
		startLocationCountryName: string | null;
		startLocationStateName: string | null;
		endLocationId: number;
		endLocationName: string | null;
		firstName: string | null;
		lastName: string | null;
		address1: string | null;
		address2: string | null;
		city: string | null;
		stateCode: string | null;
		productionName: string | null;
		countryName: string;
		zipCode: string | null;
		dateOfBirth: string | null;
		customerType: string | null;
		phone: string | null;
		hPhone: string | null;
		bPhone: string | null;
		cPhone: string | null;
		email: string | null;
		company: string | null;
		vehicleTypeId: number;
		vehicleType: string | null;
		modelId: number;
		modelName: string | null;
		canceledDate: string | null;
		basePrice: number;
		note: string | null;
		agreementId: number | null;
		agreementNumber: string | null;
		cancellationCharge: null;
		advancedPayment: number;
		creditCardExpiryDate: string | null;
		creditCardNo: string | null;
		creditCardType: string | null;
		creditCardCVSNo: string | null;
		ldw: number;
		tldw: number;
		specialNote: string | null;
		promotionId: number;
		deposit: number;
		logId: number;
		creditCardBillingZipCode: string | null;
		imageName: string | null;
		totalDays: number;
		isCompound: boolean;
		fullDepositAmount: number;
		installmentAmount: number;
		perInstallmentAmount: number;
		installmentQty: number;
		preAdjustment: number;
		reservationPrimaryId: number;
		prep: boolean;
		wrap: boolean;
		vehicleTypeId2: number | null;
		vehicleId2: number | null;
		vehicleMakeName2: string | null;
		modelName2: string | null;
		year2: number | null;
		licenseNo2: string | null;
		vehicleNo2: string | null;
		vehicleType2: string | null;
		poNo: string | null;
		roNo: string | null;
		poNo2: string | null;
		roNo2: string | null;
		totalDiscount: number;
		locationId: number;
		daysInWeek: number;
		createdBy: string | null;
		lastUpdateByName: string | null;
		reservationStatus: number;
		isRetrieval: boolean;
		isDelivery: boolean;
		projectedMileage: number | null;
		referralId: number | null;
		voucherNo: string | null;
		locationEmail: string | null;
		locationEmailName: string | null;
		referralCommission: number;
		totalRows: number;
		createdById: number;
	};
	miscChargeList: ReservationMiscViewDataFull[];
	taxList: {
		taxId: number;
		name: string;
		description: string | null;
		value: number;
		isOption: false;
		isSelected: false;
		locationId: number;
		taxValue: number;
		locationName: string | null;
		locationTaxID: number;
		createdBy: number;
		createdByName: string | null;
		lastUpdatedByName: string | null;
		activeDate: string | null;
		expiryDate: string | null;
		activeDatestr: string | null;
		expiryDatestr: string | null;
		taxSelectedStatus: string | null;
	}[];
	rateDetailsList: [] | null;
	reservationTotal: number | null;
	reservationAttributeList: [];
	paymentList: [];
	clientPdfTemplatesList: string[];
	emailTrackList: [];
	depositTotals: {
		depositAmount: number;
		onHoldAmount: number;
		refundAmount: number;
		releaseAmount: number;
		forfeitureAmount: number;
		totalCanceledAmount: number;
	};
	invoiceList: null;
	reservtionBillingReview: {
		billingInfoID: number;
		reservationID: number;
		contactName: string | null;
		contactAddress: string | null;
		contactPhone: string | null;
		contactEmail: string | null;
		isActive: boolean;
		billingBy: string;
		creditCardReferenceId: number | null;
		billingOwnerId: number;
	};
	reservationBillingList: [];
	mileageCharges: [];
	agreementReservationMileageBreakdown: [];
	navDynamicAttribute: null;
	agreementInsurance: null;
	customerImages: [];
}
