export interface AgreementInList {
	AgreementId: number;
	CreditCardNo: string;
	ReserveId: number | null;
	VehicleId: number;
	MakeId: number;
	VehicleNo: string;
	VehicleMakeName: string;
	ModelId: number;
	ModelName: string;
	Year: number;
	Trim: string | null;
	LicenseNo: string;
	CheckoutDate: string;
	CheckinDate: string;
	ReturnDate: string;
	CreatedDate: string;
	CreatedByName: string;
	CustomerId: number;
	FirstName: string;
	LastName: string;
	PONo: string | null;
	RONo: string | null;
	HPhone: string | null;
	CPhone: string | null;
	BPhone: string | null;
	AgreementStatusId: number;
	AgreementNumber: string;
	TotalAmount: number;
	Note: string | null;
	Color: string;
	AgreementStatusName: string;
	CheckoutLocationId: number;
	CheckinLocationId: number;
	CheckoutLocationName: string;
	CheckinLocationName: string;
	VehicleTypeId: number;
	VehicleType: string;
}

export interface AgreementDataFull {
	agreementId: number;
	agreementNumber: string;
	checkinDate: string;
	checkoutDate: string;
	customerId: number;
	clientId: number;
	rentalReason: string | null;
	lowestRate: boolean | null;
	odometerOut: number | null;
	odometerIn: number | null;
	fuelLevelOut: string | null;
	fuelLevelIn: string | null;
	totalAmount: number;
	advancePaid: number;
	paymentMethod: string;
	extraHourlyRate: number;
	firstName: string | null;
	lastName: string | null;
	hPhone: string | null;
	bPhone: string | null;
	cPhone: string | null;
	billingAddress1: null;
	rateLocationName: string | null;
	rateLocation: string | null;
	companyName: null;
	address1: string | null;
	address2: string | null;
	city: string | null;
	stateId: number;
	stateName: string;
	countryId: number;
	countryName: string | null;
	zipCode: string | null;
	email: string | null;
	creditCardType: null;
	creditCardNo: string | null;
	creditCardCVSNo: null;
	creditCardExpiryDate: null;
	licenseExpiryDate: string | null;
	customerLicenseNumber: string | null;
	licenseIssueState: string | null;
	insuranceExpiryDate: string | null;
	checkoutLocation: number;
	checkoutLocationName: string;
	checkoutLocationAddress1: string;
	checkoutLocationAddress2: null;
	checkoutLocationCity: string | null;
	checkoutLocationEmail: string | null;
	checkoutLocationEmailName: null;
	checkoutLocationState: string;
	checkoutLocationCountry: string;
	checkoutLocationPhone: string | null;
	checkinLocation: number;
	checkoutinLocationName: null;
	vehicleId: number | null;
	vehicleId2: number | null;
	vehicleTypeId: number;
	vehicleNo: string;
	vehicleType: string;
	makeId: number;
	vehicleMakeName: string;
	modelId: number;
	modelName: string;
	trim: number | null;
	year: number;
	origionalOdometer: number;
	currentOdometer: number;
	fuelLevel: string;
	licenseNo: string;
	takeSize: number;
	statusId: number;
	createdDate: string;
	status: number;
	rateId: number;
	rateName: string;
	hourlyRate: number | null;
	dailyRate: number | null;
	extraDaily: number | null;
	weeklyRate: number | null;
	extraWeekllyRate: number;
	fuelCharge: number | null;
	kMorMileageCharge: number | null;
	monthlyRate: number | null;
	kmDaily: number | null;
	kmWeekly: number | null;
	kmMonthly: number | null;
	deliveryDate: string;
	returnDate: string | null;
	returnLocation: number;
	returnLocationName: string;
	kmCharge: number;
	additionalCharge: number;
	extraDayCharge: number;
	extraKMCharge: number;
	extraFuelCharge: number;
	referralId: number;
	voucherNo: string | null;
	maxLDW: number;
	maxTLDW: number;
	hourlyQty: number;
	dailyQty: number;
	weeklyQty: number;
	monthlyQty: number;
	extraHourlyQty: number;
	extraMonthlyQty: number;
	extraWeeklyQty: number;
	extraDailyQty: number;
	amountPaid: number;
	balanceDue: number;
	returnPaymentMethod: string | null;
	destination: string | null;
	returnVehicleStatus: string;
	discount: number;
	subTotal: number;
	baseCharge: number;
	unTaxableAdditional: number;
	extraDays: number;
	specialRate: number | null;
	kmSpecial: number | null;
	specialQty: number | null;
	extraSpecialQty: number;
	extraSpecialRate: number | null;
	additionalCharges: number;
	poNo: string | null;
	roNo: string | null;
	maintenanceEvery: number;
	creditCardBillingZipCode: null;
	createdByName: string;
	deposit: number;
	promoCodeId: number;
	promotionDiscount: number;
	fullDepositAmount: number;
	installmentAmount: number;
	perInstallmentAmount: number;
	installmentQty: number;
	isCompound: boolean;
	totlDays: number;
	agreementPrimaryId: number;
	prep: number;
	wrap: number;
	vehicleTypeId2: number | null;
	poNo2: string | null;
	roNo2: string | null;
	licenseNo2: string | null;
	vehicleNo2: string | null;
	year2: string | null;
	vehicleType2: string | null;
	vehicleMakeName2: string | null;
	modelName2: string | null;
	isRiskAgreement: boolean | null;
	riskNote: string | null;
	riskDate: string | null;
	specialNote: string | null;
	note: string | null;
	contractReason: number;
	changedDate: string;
	contractExtendedPerioid: number;
	contractExtendReasonDesc: null;
	daysInWeek: number;
	lastUpdatedBy: string;
	checkedInByName: string;
	agreementStatusId: number;
	isDelivery: boolean;
	isRetrieval: boolean;
	projectMileage: number | null;
	retrivalCode: string | null;
	signatureName: string | null;
	referralName: string | null;
	contactName: string | null;
	address: string | null;
	contactPhone: null;
	referralCommission: number | null;
	initialRateTotal: number;
	finalRateTotal: number;
	totMisChargTaxable: number;
	totMisChargNonTaxable: number;
	totalTax: number;
	sourceId: number;
	isDeliveryOld: boolean;
	isRetrievalOld: boolean;
	reimbursementAmount: number;
	depositTotals: {
		depositAmount: number;
		onHoldAmount: number;
		refundAmount: number;
		releaseAmount: number;
		forfeitureAmount: number;
		totalCanceledAmount: number;
	};
}

export interface AgreementSummary {
	baseRate: number;
	totalDays: number;
	miscCharges: [];
	totalMiscChargesTaxable: number;
	totalMiscChargesNonTaxable: number;
	subTotal: number;
	totalTax: number;
	dropOffCharges: number;
	total: number;
	promotionDiscount: number;
	rateSummaryItems: {
		type: string;
		rate: number;
		units: number;
		startDate: string;
		endDate: string;
		kMorMileageAllowed: number;
	}[];
	avgPerDayRate: number;
	taxes: {
		taxId: number;
		locationTaxId: number;
		name: string;
		description: string;
		value: number;
		isOption: false;
		isDeleted: false;
		isDefaultSelectedForReservation: boolean;
		misChargeId: string | null;
	}[];
	promotions: null;
	maxTotalDays: number;
	freeMiles: number;
	extraMilesCharge: number;
	initialCharge: number;
	initialChargeHours: number;
	avgPerHourRate: number;
	advancePayment: number | null;
	balanceDue: number;
	inventoryCharges: number | null;
	totalInventoryChargesTaxable: number;
	totalInventoryChargesNonTaxable: number;
	finalBaseRate: number;
}
