export interface CustomersInList {
	CustomerId: number;
	CustomerNumber: string | null;
	CompanyName: string | null;
	FirstName: string | null;
	MiddleName: string | null;
	LastName: string | null;
	DateOfbirth: string | null;
	Address1: string | null;
	Address2: string | null;
	ZipCode: string | null;
	City: string | null;
	StateId: number;
	CountryId: number;
	hPhone: string | null;
	bPhone: string | null;
	cPhone: string | null;
	Fax: string | null;
	LicenseNumber: string | null;
	LicenseCategory: string | null;
	Email: string | null;
	HSTNumber: string | null;
	Active: boolean;
	CountryName: string | null;
	StateName: string | null;
	StateCode: number | null;
	InsuranceCompany: string | null;
	PolicyNumber: string | null;
	InsuranceExpiryDate: string | null;
	InsuranceCountry: number | null;
	InsuranceProvince: number | null;
	CreditCardType: string | null;
	CreditCardNo: string | null;
	CreditCardExpiryDate: string | null;
	CreditCardCVSNo: string | null;
	InsuranceState: string | null;
	BillingAddress1: string | null;
	BillingCity: string | null;
	BillingZipCord: string | null;
	InsuranceClaim: string | null;
	BillStateName: string | null;
	BillingStateId: number | null;
	BillingCountyId: number | null;
	CustomerType: string | null;
	BillCountryName: string | null;
	Password: string | null;
	LicenseIssueDate: string | null;
	LicenseExpiryDate: string | null;
	LicenseIssueState: null;
	PassportNo: string | null;
	PassportIssueDate: string | null;
	PassportExpairyDate: string | null;
	LocationId: number | null;
	LocationName: string | null;
	CreditCardBillingZipCode: string | null;
	RateName: string | null;
	ProductionName: string | null;
	NameOnCard: string | null;
	CustomerImage: string | null;
	DrivingExperience: string | null;
	IsBlackListed: boolean;
	BlackListId: number;
	BlackListDescription: string | null;
	BlackListDate: string | null;
	BlackListReason: number;
	LicenseCountryId: string | null;
	AccoutNameInBank: string | null;
	AccountNumber: string | null;
	BSB: string | null;
	EmergencyContactNo: string | null;
	CompanyRegNo: string | null;
	IsSMSOpted: boolean;
	IsEmailOpted: boolean;
	QboReferenceId: string | null;
	TicketFlag: number | null;
	ClientId: number;
	CreatedBy: number;
	UserName: string | null;
}
