export interface VehiclesInList {
	VehicleId: number;
	VehicleNo: string;
	ModelId: number;
	MakeId: number;
	VehicleMakeName: string;
	ModelName: string;
	Year: number;
	Active: boolean;
	LicenseNo: string;
	LicenseState: string | null;
	OwningLocationId: number;
	OwningLocationName: string;
	Color: string;
	CurrentLocationId: number;
	CurrentLocationName: string;
	StatusId: number;
	VehicleTypeId: number;
	VehicleType: string;
	CurrentOdometer: number;
	Transmission: string;
	Cylinders: number;
	Memo: string | null;
	FuelLevel: string;
	TankSize: number;
	CreatedBy: string | null;
	LeasingCompanyName: string | null;
	InsuranceCompanyName: string | null;
	FuelType: string;
	LeaseAmt: number;
	DownPayment: number;
	CashValue: number;
	Vin: string | null;
	Replaced: boolean;
	VehicleStatus: string;
	VehicleImage: string;
}
