import { AvailableLocation } from "../interfaces/locations/location";
import { ReservationViewDataFull } from "../interfaces/reservations/reservationView";
import { VehiclesInList } from "../interfaces/vehicles/vehicleSearch";
export const fakeVehicleDataInList: VehiclesInList[] = [
	{
		VehicleId: 137328,
		VehicleNo: "15292",
		ModelId: 18631043,
		MakeId: 118459,
		VehicleMakeName: "Jeep",
		ModelName: "Cherokee",
		Year: 2019,
		Active: true,
		LicenseNo: "L-082K",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "White",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 11,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 180,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 25,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1N6AA07A06N554275",
		Replaced: false,
		VehicleStatus: "Sold",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/5sw4fgc4yej.jpg",
	},
	{
		VehicleId: 137332,
		VehicleNo: "15294",
		ModelId: 18630684,
		MakeId: 118441,
		VehicleMakeName: "Chrysler",
		ModelName: "300M",
		Year: 2019,
		Active: true,
		LicenseNo: "XKK-4569",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Black",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25635,
		VehicleType: "Full Size",
		CurrentOdometer: 390,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 25,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "JM3ER2A50C0415350",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/qoajo3np4zq.jpg",
	},
	{
		VehicleId: 137333,
		VehicleNo: "15255",
		ModelId: 18631066,
		MakeId: 118460,
		VehicleMakeName: "Kia",
		ModelName: "Optima",
		Year: 2018,
		Active: true,
		LicenseNo: "ADA A11",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "White",
		CurrentLocationId: 15548,
		CurrentLocationName: "DrivePro - Huntsville",
		StatusId: 8,
		VehicleTypeId: 25634,
		VehicleType: "Mid-Size",
		CurrentOdometer: 350,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 30,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1G3EZ57Y2FE333865",
		Replaced: false,
		VehicleStatus: "InService",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/gzeka2mjuw3.jpg",
	},
	{
		VehicleId: 137334,
		VehicleNo: "16210",
		ModelId: 18630932,
		MakeId: 118453,
		VehicleMakeName: "Honda",
		ModelName: "Accord",
		Year: 2019,
		Active: true,
		LicenseNo: "7AJG573",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Red",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25634,
		VehicleType: "Mid-Size",
		CurrentOdometer: 260,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 30,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "2G1WF55K229260613",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/fi5urwuwn2j.jpg",
	},
	{
		VehicleId: 137336,
		VehicleNo: "16211",
		ModelId: 18631164,
		MakeId: 118468,
		VehicleMakeName: "Mazda",
		ModelName: "MAZDA6",
		Year: 2020,
		Active: true,
		LicenseNo: "472 5012",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Black",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25634,
		VehicleType: "Mid-Size",
		CurrentOdometer: 110,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 25,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "2HNYD18684H558809",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/lw5e1sylghe.jpg",
	},
	{
		VehicleId: 137337,
		VehicleNo: "17815",
		ModelId: 18636261,
		MakeId: 118460,
		VehicleMakeName: "Kia",
		ModelName: "Seltos",
		Year: 2020,
		Active: true,
		LicenseNo: "FLD-4684",
		LicenseState: null,
		OwningLocationId: 15548,
		OwningLocationName: "DrivePro - Huntsville",
		Color: "White",
		CurrentLocationId: 15548,
		CurrentLocationName: "DrivePro - Huntsville",
		StatusId: 4,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 105,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "ThreeQuarter",
		TankSize: 22,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1FDXR82E9TVA05096",
		Replaced: false,
		VehicleStatus: "Grounded",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/5uzpevan3r1.jpg",
	},
	{
		VehicleId: 137338,
		VehicleNo: "17820",
		ModelId: 18630457,
		MakeId: 118434,
		VehicleMakeName: "Audi",
		ModelName: "Q3",
		Year: 2017,
		Active: true,
		LicenseNo: "AEC B56",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Grey",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 20304,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 27,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "2C3JA63H25H521024",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/xdc5igp22g1.jpg",
	},
	{
		VehicleId: 137339,
		VehicleNo: "18520",
		ModelId: 18630672,
		MakeId: 118441,
		VehicleMakeName: "Chrysler",
		ModelName: "Pacifica",
		Year: 2018,
		Active: true,
		LicenseNo: "HBP-1920",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Grey",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25637,
		VehicleType: "Mini Van",
		CurrentOdometer: 490,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 33,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1FTNX21L02EA70450",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/ch2ii2sl5se.jpg",
	},
	{
		VehicleId: 137345,
		VehicleNo: "11283",
		ModelId: 18630808,
		MakeId: 118450,
		VehicleMakeName: "Ford",
		ModelName: "Transit Cargo",
		Year: 2016,
		Active: true,
		LicenseNo: "LMH-324",
		LicenseState: null,
		OwningLocationId: 15548,
		OwningLocationName: "DrivePro - Huntsville",
		Color: "Red",
		CurrentLocationId: 15548,
		CurrentLocationName: "DrivePro - Huntsville",
		StatusId: 2,
		VehicleTypeId: 25637,
		VehicleType: "Mini Van",
		CurrentOdometer: 273,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 35,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1G1JA5SH3F4132309",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/ibqeppwyzks.jpg",
	},
	{
		VehicleId: 137346,
		VehicleNo: "11394",
		ModelId: 18630930,
		MakeId: 118453,
		VehicleMakeName: "Honda",
		ModelName: "CR-V",
		Year: 2018,
		Active: true,
		LicenseNo: "AXE-823",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Blue",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 311,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "OneEight",
		TankSize: 31,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1FTFW1EF0BKD67418",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/nu1nbtm23so.jpg",
	},
];

export const fakeViewReservation: ReservationViewDataFull = {
	reservationview: {
		reserveId: 367965,
		additionalCharge: 0.0,
		reservationNumber: "256-WalkIn",
		reservationType: "Walkin",
		owningLocationId: 15545,
		lowestRate: null,
		clientId: 1013,
		customerId: 784575,
		vehicleId: 144916,
		vehicleMakeName: "Audi",
		trim: null,
		year: 2020,
		startDate: "2021-06-26T09:00:00",
		endDate: "2021-07-02T09:00:00",
		createdDate: "2021-06-25T19:12:17.133",
		notes: null,
		licenseNo: "DIH-604",
		vehicleNo: "604",
		fuelType: "Petrol",
		fuelLevel: "Full",
		transmission: "Automatic",
		currentOdometer: 51,
		color: "Black",
		doors: 4,
		vin: "1G2NF52E84C254604",
		statusId: 2,
		insuranceAmt: null,
		startLocationId: 15545,
		startLocationName: "DrivePro - Houston",
		startLocationAddress1: "3333 Raleigh St",
		startLocationAddress2: null,
		startLocationCity: "Houston",
		startLocationPhone: "38659345876",
		startLocationCountryName: "USA",
		startLocationStateName: "TEXAS",
		endLocationId: 15545,
		endLocationName: "DrivePro - Houston",
		firstName: "Darren",
		lastName: "Yusef",
		address1: "03 Kings Road",
		address2: null,
		city: "Housten",
		stateCode: "TX",
		productionName: null,
		countryName: "USA",
		zipCode: "30612",
		dateOfBirth: "1989-11-01T00:00:00",
		customerType: "Online",
		phone: "07495749462",
		hPhone: "07495749462",
		bPhone: "07495749462",
		cPhone: null,
		email: "darrenyusef1978@gmail.com",
		company: null,
		vehicleTypeId: 25635,
		vehicleType: "Full Size",
		modelId: 18630453,
		modelName: "A5",
		canceledDate: null,
		basePrice: 180.0,
		note: null,
		agreementId: null,
		agreementNumber: null,
		cancellationCharge: null,
		advancedPayment: 0.0,
		creditCardExpiryDate: "2026-03-31T00:00:00",
		creditCardNo: "YOnKYHPkt0+GwYgHjySZA6j6GvQ9snz/JtmaaMfVPZM=",
		creditCardType: "Visa",
		creditCardCVSNo: "956",
		ldw: 0.0,
		tldw: 0.0,
		specialNote: null,
		promotionId: 0,
		deposit: 80.0,
		logId: 0,
		creditCardBillingZipCode: null,
		imageName: "l2ngm40j1fw.jpg",
		totalDays: 6,
		isCompound: false,
		fullDepositAmount: 0.0,
		installmentAmount: 0.0,
		perInstallmentAmount: 0.0,
		installmentQty: 0,
		preAdjustment: 0.0,
		reservationPrimaryId: 0,
		prep: false,
		wrap: false,
		vehicleTypeId2: null,
		vehicleId2: null,
		vehicleMakeName2: null,
		modelName2: null,
		year2: null,
		licenseNo2: null,
		vehicleNo2: null,
		vehicleType2: null,
		poNo: null,
		roNo: null,
		poNo2: null,
		roNo2: null,
		totalDiscount: 0.0,
		locationId: 15545,
		daysInWeek: 0,
		createdBy: "Sean Cassiere",
		lastUpdateByName: "Sean Cassiere",
		reservationStatus: 2,
		isRetrieval: false,
		isDelivery: false,
		projectedMileage: null,
		referralId: null,
		voucherNo: null,
		locationEmail: "sean@navotar.com",
		locationEmailName: "Sean Houston",
		referralCommission: 0.0,
		totalRows: 0,
		createdById: 24877,
	},
	miscChargeList: [
		{
			miscChargeId: 2,
			miscChargeCode: 2,
			unit: 1,
			name: "Personal Accident Insurance",
			description: "Personal Accident Insurance",
			calculationType: "Fixed",
			taxNotAvailable: false,
			isCommission: false,
			value: 15.0,
			totalValue: 15.0,
			startDate: "2021-06-25T09:42:17.197",
			endDate: "2021-06-25T09:42:17.197",
			quantity: 0,
			createdDate: "2021-06-25T19:12:17.133",
			gLcode: null,
			locationMiscChargeId: 0,
			isChargeByPeriod: false,
			isTaxable: true,
			locationTaxIds: "2,1074",
			isSelected: false,
			isQuantity: false,
			locationMiscChargeID: 44347,
			vehicleTypeId: 0,
			miscChargeID: 0,
			misChargeCode: 0,
			isOptional: false,
			printValue: null,
			oldStartDateString: null,
			oldEndDateString: null,
			startDateString: null,
			createddateString: null,
			endDateString: null,
			isDeleted: false,
			isFreeze: false,
			isAlreadySelected: false,
			isDeductible: false,
			locationId: 0,
			locationName: null,
			vehicleType: null,
			miscTaxList: null,
			totaltax: 0.0,
			subTotal: 0.0,
			amountPaid: null,
			amountRemaining: null,
			miscchargeTypeId: 0,
			option: 0,
			misChargeOptionList: null,
			optionId: null,
		},
		{
			miscChargeId: 33,
			miscChargeCode: 15,
			unit: 6,
			name: "Unlimited KM",
			description: "Unlimited KM",
			calculationType: "Perday",
			taxNotAvailable: false,
			isCommission: false,
			value: 70.0,
			totalValue: 420.0,
			startDate: "2021-06-25T09:42:17.243",
			endDate: "2021-06-25T09:42:17.243",
			quantity: 0,
			createdDate: "2021-06-25T19:12:17.133",
			gLcode: null,
			locationMiscChargeId: 0,
			isChargeByPeriod: false,
			isTaxable: true,
			locationTaxIds: "2",
			isSelected: false,
			isQuantity: false,
			locationMiscChargeID: 44429,
			vehicleTypeId: 0,
			miscChargeID: 0,
			misChargeCode: 0,
			isOptional: false,
			printValue: null,
			oldStartDateString: null,
			oldEndDateString: null,
			startDateString: null,
			createddateString: null,
			endDateString: null,
			isDeleted: false,
			isFreeze: false,
			isAlreadySelected: false,
			isDeductible: false,
			locationId: 0,
			locationName: null,
			vehicleType: null,
			miscTaxList: null,
			totaltax: 0.0,
			subTotal: 0.0,
			amountPaid: null,
			amountRemaining: null,
			miscchargeTypeId: 0,
			option: 0,
			misChargeOptionList: null,
			optionId: null,
		},
		{
			miscChargeId: 14401,
			miscChargeCode: 0,
			unit: 1,
			name: "SMOKING FEE",
			description: "SMOKING FEE",
			calculationType: "Fixed",
			taxNotAvailable: false,
			isCommission: false,
			value: 10.0,
			totalValue: 10.0,
			startDate: "2021-06-25T13:46:20.897",
			endDate: "2021-06-25T13:46:20.897",
			quantity: 0,
			createdDate: "2021-06-25T23:16:20.753",
			gLcode: null,
			locationMiscChargeId: 0,
			isChargeByPeriod: false,
			isTaxable: false,
			locationTaxIds: "2",
			isSelected: false,
			isQuantity: false,
			locationMiscChargeID: 46388,
			vehicleTypeId: 0,
			miscChargeID: 0,
			misChargeCode: 0,
			isOptional: false,
			printValue: null,
			oldStartDateString: null,
			oldEndDateString: null,
			startDateString: null,
			createddateString: null,
			endDateString: null,
			isDeleted: false,
			isFreeze: false,
			isAlreadySelected: false,
			isDeductible: false,
			locationId: 0,
			locationName: null,
			vehicleType: null,
			miscTaxList: null,
			totaltax: 0.0,
			subTotal: 0.0,
			amountPaid: null,
			amountRemaining: null,
			miscchargeTypeId: 0,
			option: 0,
			misChargeOptionList: null,
			optionId: null,
		},
		{
			miscChargeId: 14576,
			miscChargeCode: 0,
			unit: 1,
			name: "Child Seat (3Years +)",
			description: "Child Seat for 3 year old children and above.",
			calculationType: "Fixed",
			taxNotAvailable: false,
			isCommission: false,
			value: 15.0,
			totalValue: 15.0,
			startDate: "2021-06-25T10:08:38.45",
			endDate: "2021-06-25T10:08:38.45",
			quantity: 2,
			createdDate: "2021-06-25T19:38:38.117",
			gLcode: null,
			locationMiscChargeId: 0,
			isChargeByPeriod: false,
			isTaxable: true,
			locationTaxIds: "2",
			isSelected: false,
			isQuantity: true,
			locationMiscChargeID: 46525,
			vehicleTypeId: 0,
			miscChargeID: 0,
			misChargeCode: 0,
			isOptional: false,
			printValue: null,
			oldStartDateString: null,
			oldEndDateString: null,
			startDateString: null,
			createddateString: null,
			endDateString: null,
			isDeleted: false,
			isFreeze: false,
			isAlreadySelected: false,
			isDeductible: false,
			locationId: 0,
			locationName: null,
			vehicleType: null,
			miscTaxList: null,
			totaltax: 0.0,
			subTotal: 0.0,
			amountPaid: null,
			amountRemaining: null,
			miscchargeTypeId: 0,
			option: 0,
			misChargeOptionList: null,
			optionId: null,
		},
		{
			miscChargeId: 14820,
			miscChargeCode: 0,
			unit: 6,
			name: "Loss Damage Waiver",
			description: "Primary Loss Damage Waiver",
			calculationType: "Perday",
			taxNotAvailable: false,
			isCommission: false,
			value: 15.0,
			totalValue: 90.0,
			startDate: "2021-06-25T09:42:17.273",
			endDate: "2021-06-25T09:42:17.273",
			quantity: 0,
			createdDate: "2021-06-25T19:12:17.133",
			gLcode: null,
			locationMiscChargeId: 0,
			isChargeByPeriod: false,
			isTaxable: true,
			locationTaxIds: "2,1074",
			isSelected: false,
			isQuantity: false,
			locationMiscChargeID: 48052,
			vehicleTypeId: 0,
			miscChargeID: 0,
			misChargeCode: 0,
			isOptional: false,
			printValue: null,
			oldStartDateString: null,
			oldEndDateString: null,
			startDateString: null,
			createddateString: null,
			endDateString: null,
			isDeleted: false,
			isFreeze: false,
			isAlreadySelected: false,
			isDeductible: true,
			locationId: 0,
			locationName: null,
			vehicleType: null,
			miscTaxList: null,
			totaltax: 0.0,
			subTotal: 0.0,
			amountPaid: null,
			amountRemaining: null,
			miscchargeTypeId: 0,
			option: 0,
			misChargeOptionList: null,
			optionId: null,
		},
		{
			miscChargeId: 15129,
			miscChargeCode: 0,
			unit: 1,
			name: "Pickup and Drop-off Fee",
			description: "A fee for pick or drop off",
			calculationType: "Fixed",
			taxNotAvailable: false,
			isCommission: false,
			value: 75.0,
			totalValue: 75.0,
			startDate: "2021-06-25T09:42:17.307",
			endDate: "2021-06-25T09:42:17.307",
			quantity: 0,
			createdDate: "2021-06-25T19:12:17.133",
			gLcode: null,
			locationMiscChargeId: 0,
			isChargeByPeriod: false,
			isTaxable: true,
			locationTaxIds: "2,1301",
			isSelected: false,
			isQuantity: false,
			locationMiscChargeID: 49720,
			vehicleTypeId: 0,
			miscChargeID: 0,
			misChargeCode: 0,
			isOptional: false,
			printValue: null,
			oldStartDateString: null,
			oldEndDateString: null,
			startDateString: null,
			createddateString: null,
			endDateString: null,
			isDeleted: false,
			isFreeze: false,
			isAlreadySelected: false,
			isDeductible: true,
			locationId: 0,
			locationName: null,
			vehicleType: null,
			miscTaxList: null,
			totaltax: 0.0,
			subTotal: 0.0,
			amountPaid: null,
			amountRemaining: null,
			miscchargeTypeId: 0,
			option: 0,
			misChargeOptionList: null,
			optionId: null,
		},
	],
	taxList: [
		{
			taxId: 2,
			name: "GST",
			description: "Goods & Services",
			value: 6.0,
			isOption: false,
			isSelected: false,
			locationId: 0,
			taxValue: 0.0,
			locationName: null,
			locationTaxID: 0,
			createdBy: 0,
			createdByName: null,
			lastUpdatedByName: null,
			activeDate: null,
			expiryDate: null,
			activeDatestr: null,
			expiryDatestr: null,
			taxSelectedStatus: null,
		},
	],
	rateDetailsList: null,
	reservationTotal: null,
	reservationAttributeList: [],
	paymentList: [],
	clientPdfTemplatesList: [],
	emailTrackList: [],
	depositTotals: {
		depositAmount: 80.0,
		onHoldAmount: 0.0,
		refundAmount: 0.0,
		releaseAmount: 0.0,
		forfeitureAmount: 0.0,
		totalCanceledAmount: 0.0,
	},
	invoiceList: null,
	reservtionBillingReview: {
		billingInfoID: 60293,
		reservationID: 367965,
		contactName: "Darren Yusef",
		contactAddress: "03 Kings Road  Housten TEXAS USA 30612",
		contactPhone: "07495749462",
		contactEmail: "darrenyusef1978@gmail.com",
		isActive: true,
		billingBy: "Customer",
		creditCardReferenceId: null,
		billingOwnerId: 784575,
	},
	reservationBillingList: [],
	mileageCharges: [],
	agreementReservationMileageBreakdown: [],
	navDynamicAttribute: null,
	agreementInsurance: null,
	customerImages: [],
};

export const fakeActiveLocations: AvailableLocation[] = [
	{
		locationId: 15545,
		stateName: "TEXAS",
		countryName: "USA",
		locationName: "DrivePro - Houston",
		address1: "3333 Raleigh St",
		address2: null,
		city: "Houston",
	},
	{
		locationId: 15548,
		stateName: "ALABAMA",
		countryName: "USA",
		locationName: "DrivePro - Huntsville",
		address1: "933 Explorer Blvd NW",
		address2: null,
		city: "Huntsville",
	},
];
