import { VehiclesInList } from "../interfaces/vehicles";
export const fakeVehicleDataInList: VehiclesInList[] = [
	{
		VehicleId: 137328,
		VehicleNo: "15292",
		ModelId: 18631043,
		MakeId: 118459,
		VehicleMakeName: "Jeep",
		ModelName: "Cherokee",
		Year: 2019,
		Active: true,
		LicenseNo: "L-082K",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "White",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 11,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 180,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 25,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1N6AA07A06N554275",
		Replaced: false,
		VehicleStatus: "Sold",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/5sw4fgc4yej.jpg",
	},
	{
		VehicleId: 137332,
		VehicleNo: "15294",
		ModelId: 18630684,
		MakeId: 118441,
		VehicleMakeName: "Chrysler",
		ModelName: "300M",
		Year: 2019,
		Active: true,
		LicenseNo: "XKK-4569",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Black",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25635,
		VehicleType: "Full Size",
		CurrentOdometer: 390,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 25,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "JM3ER2A50C0415350",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/qoajo3np4zq.jpg",
	},
	{
		VehicleId: 137333,
		VehicleNo: "15255",
		ModelId: 18631066,
		MakeId: 118460,
		VehicleMakeName: "Kia",
		ModelName: "Optima",
		Year: 2018,
		Active: true,
		LicenseNo: "ADA A11",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "White",
		CurrentLocationId: 15548,
		CurrentLocationName: "DrivePro - Huntsville",
		StatusId: 8,
		VehicleTypeId: 25634,
		VehicleType: "Mid-Size",
		CurrentOdometer: 350,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 30,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1G3EZ57Y2FE333865",
		Replaced: false,
		VehicleStatus: "InService",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/gzeka2mjuw3.jpg",
	},
	{
		VehicleId: 137334,
		VehicleNo: "16210",
		ModelId: 18630932,
		MakeId: 118453,
		VehicleMakeName: "Honda",
		ModelName: "Accord",
		Year: 2019,
		Active: true,
		LicenseNo: "7AJG573",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Red",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25634,
		VehicleType: "Mid-Size",
		CurrentOdometer: 260,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 30,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "2G1WF55K229260613",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/fi5urwuwn2j.jpg",
	},
	{
		VehicleId: 137336,
		VehicleNo: "16211",
		ModelId: 18631164,
		MakeId: 118468,
		VehicleMakeName: "Mazda",
		ModelName: "MAZDA6",
		Year: 2020,
		Active: true,
		LicenseNo: "472 5012",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Black",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25634,
		VehicleType: "Mid-Size",
		CurrentOdometer: 110,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 25,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "2HNYD18684H558809",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/lw5e1sylghe.jpg",
	},
	{
		VehicleId: 137337,
		VehicleNo: "17815",
		ModelId: 18636261,
		MakeId: 118460,
		VehicleMakeName: "Kia",
		ModelName: "Seltos",
		Year: 2020,
		Active: true,
		LicenseNo: "FLD-4684",
		LicenseState: null,
		OwningLocationId: 15548,
		OwningLocationName: "DrivePro - Huntsville",
		Color: "White",
		CurrentLocationId: 15548,
		CurrentLocationName: "DrivePro - Huntsville",
		StatusId: 4,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 105,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "ThreeQuarter",
		TankSize: 22,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1FDXR82E9TVA05096",
		Replaced: false,
		VehicleStatus: "Grounded",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/5uzpevan3r1.jpg",
	},
	{
		VehicleId: 137338,
		VehicleNo: "17820",
		ModelId: 18630457,
		MakeId: 118434,
		VehicleMakeName: "Audi",
		ModelName: "Q3",
		Year: 2017,
		Active: true,
		LicenseNo: "AEC B56",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Grey",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 20304,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 27,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "2C3JA63H25H521024",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/xdc5igp22g1.jpg",
	},
	{
		VehicleId: 137339,
		VehicleNo: "18520",
		ModelId: 18630672,
		MakeId: 118441,
		VehicleMakeName: "Chrysler",
		ModelName: "Pacifica",
		Year: 2018,
		Active: true,
		LicenseNo: "HBP-1920",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Grey",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25637,
		VehicleType: "Mini Van",
		CurrentOdometer: 490,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 33,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1FTNX21L02EA70450",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/ch2ii2sl5se.jpg",
	},
	{
		VehicleId: 137345,
		VehicleNo: "11283",
		ModelId: 18630808,
		MakeId: 118450,
		VehicleMakeName: "Ford",
		ModelName: "Transit Cargo",
		Year: 2016,
		Active: true,
		LicenseNo: "LMH-324",
		LicenseState: null,
		OwningLocationId: 15548,
		OwningLocationName: "DrivePro - Huntsville",
		Color: "Red",
		CurrentLocationId: 15548,
		CurrentLocationName: "DrivePro - Huntsville",
		StatusId: 2,
		VehicleTypeId: 25637,
		VehicleType: "Mini Van",
		CurrentOdometer: 273,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "Full",
		TankSize: 35,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1G1JA5SH3F4132309",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/ibqeppwyzks.jpg",
	},
	{
		VehicleId: 137346,
		VehicleNo: "11394",
		ModelId: 18630930,
		MakeId: 118453,
		VehicleMakeName: "Honda",
		ModelName: "CR-V",
		Year: 2018,
		Active: true,
		LicenseNo: "AXE-823",
		LicenseState: null,
		OwningLocationId: 15545,
		OwningLocationName: "DrivePro - Houston",
		Color: "Blue",
		CurrentLocationId: 15545,
		CurrentLocationName: "DrivePro - Houston",
		StatusId: 2,
		VehicleTypeId: 25636,
		VehicleType: "SUV",
		CurrentOdometer: 311,
		Transmission: "Automatic",
		Cylinders: 0,
		Memo: null,
		FuelLevel: "OneEight",
		TankSize: 31,
		CreatedBy: null,
		LeasingCompanyName: null,
		InsuranceCompanyName: null,
		FuelType: "Diesel",
		LeaseAmt: 0.0,
		DownPayment: 0.0,
		CashValue: 0.0,
		Vin: "1FTFW1EF0BKD67418",
		Replaced: false,
		VehicleStatus: "Available",
		VehicleImage: "https://app.navotar.com/Images/VehicleImages/1013/nu1nbtm23so.jpg",
	},
];
