export type AgreementListItemType = {
  AgreementId: number;
  CreditCardNo: string | null;
  ReserveId: number | null;
  VehicleId: number;
  MakeId: number;
  VehicleNo: string;
  VehicleMakeName: string;
  ModelId: number;
  ModelName: string;
  Year: number;
  Trim: string;
  LicenseNo: string;
  CheckoutDate: string;
  CheckinDate: string;
  ReturnDate: string;
  CreatedDate: string;
  CreatedByName: string | null;
  CustomerId: number;
  FirstName: string | null;
  LastName: string | null;
  PONo: string | null;
  RONo: string | null;
  HPhone: string | null;
  CPhone: string | null;
  BPhone: string | null;
  AgreementStatusId: number;
  AgreementNumber: string;
  TotalAmount: number;
  Note: string | null;
  Color: string | null;
  AgreementStatusName: string;
  CheckoutLocationId: number;
  CheckinLocationId: number;
  CheckoutLocationName: string;
  CheckinLocationName: string;
  VehicleTypeId: number;
  VehicleType: string;
  AgreementType: string;
  CustomerType: string;
  OdometerOut: number;
  OdometerIn: number;
  CustomerEmail: string | null;
  InsurenceCompanyName: string | null;
  ClaimNumber: string | null;
  Address: string | null;
  InsuranceExpiryDate: string | null;
  Destination: string | null;
  PolicyNumber: string | null;
  RefferalName: string | null;
  AdditionalDriverNames: string | null;
  DaysRemaining: 0;
  CompanyName: string | null;
};
