export type CustomerListItemType = {
  id: string; // this is added in useGetCustomersList.ts
  CustomerId: number;
  CustomerNumber: string;
  CompanyName: string | null;
  FirstName: string;
  MiddleName: string;
  LastName: string;
  DateOfbirth: string | null;
  Address1: string | null;
  Address2: string | null;
  ZipCode: string | null;
  City: string | null;
  StateId: number;
  CountryId: number;
  hPhone: string | null;
  bPhone: string | null;
  cPhone: string | null;
  Fax: string | null;
  LicenseNumber: string | null;
  LicenseCategory: string | null;
  Email: string | null;
  HSTNumber: string | null;
  Active: boolean;
  CountryName: string;
  StateName: string;
  StateCode: number | null;
  InsuranceCompany: string;
  PolicyNumber: string;
  InsuranceExpiryDate: string | null;
  InsuranceCountry: string | null;
  InsuranceProvince: string | null;
  CreditCardType: string | null;
  CreditCardNo: "";
  CreditCardExpiryDate: string | null;
  CreditCardCVSNo: "";
  InsuranceState: string | null;
  BillingAddress1: string | null;
  BillingCity: string | null;
  BillingZipCord: string | null;
  InsuranceClaim: string | null;
  BillStateName: string | null;
  BillingStateId: string | null;
  BillingCountyId: string | null;
  CustomerType: string | null;
  BillCountryName: null;
  Password: string | null;
  LicenseIssueDate: string | null;
  LicenseExpiryDate: string | null;
  LicenseIssueState: string | null;
  PassportNo: string | null;
  PassportIssueDate: string | null;
  PassportExpairyDate: string | null;
  LocationId: number;
  LocationName: string;
  CreditCardBillingZipCode: string | null;
  RateName: string | null;
  ProductionName: string | null;
  NameOnCard: string | null;
  CustomerImage: string | null;
  DrivingExperience: string | null;
  IsBlackListed: boolean;
  BlackListId: number;
  BlackListDescription: string | null;
  BlackListDate: string | null;
  BlackListReason: number;
  LicenseCountryId: number;
  AccoutNameInBank: string | null;
  AccountNumber: string | null;
  BSB: string | null;
  EmergencyContactNo: string | null;
  CompanyRegNo: string | null;
  IsSMSOpted: boolean;
  IsEmailOpted: boolean;
  QboReferenceId: string | null;
  TicketFlag: number;
  ClientId: number;
  CreatedBy: number;
  UserName: string | null;
  PaymentTerms: number | null;
  IsTaxExempt: boolean;
  LicenseCountryName: string | null;
  BankName: string | null;
  BankSwiftCode: string | null;
  CreatedByName: string | null;
  LastUpdatedBy: string | null;
  InsuranceCountryName: string | null;
  DMSID: string | null;
  InsuranceCompanyName: string | null;
  InsuranceCompanyAddress: string | null;
  InsuranceContactPhone: string | null;
  InsuranceContactEmail: string | null;
  InsuranceProvinceName: string | null;
  CustomerImageList: string[];
  EmploymentType: string | null;
  BrokerName: string | null;
  BrokerAddress: string | null;
  BrokerPhone: string | null;
  BrokerEmail: string | null;
};
