export type ReservationListItemType = {
  id: string; // this is added in useGetReservationsList.ts
  ReserveId: number;
  AdditionalCharge: number;
  ReservationNumber: string | null;
  ReservationType: string | null;
  OwningLocationId: number;
  LowestRate: null;
  ClientId: number;
  CustomerId: number;
  VehicleId: number;
  VehicleMakeName: null;
  Trim: string | null;
  Year: number | null;
  StartDate: string | null;
  EndDate: string | null;
  CreatedDate: string | null;
  Notes: string | null;
  LicenseNo: string | null;
  VehicleNo: string | null;
  FuelType: string | null;
  FuelLevel: string | null;
  Transmission: string | null;
  CurrentOdometer: number | null;
  Color: string | null;
  Doors: string | null;
  Vin: string | null;
  StatusId: number | null;
  InsuranceAmt: number | null;
  StartLocationId: number;
  StartLocationName: string | null;
  StartLocationAddress1: string | null;
  StartLocationAddress2: string | null;
  StartLocationCity: string | null;
  StartLocationPhone: string | null;
  StartLocationCountryName: string | null;
  StartLocationStateName: string | null;
  EndLocationId: number | null;
  EndLocationName: string;
  FirstName: string | null;
  LastName: string | null;
  Address1: string | null;
  Address2: string | null;
  City: string | null;
  ProductionName: string | null;
  CountryName: string | null;
  ZipCode: string | null;
  DateOfBirth: string | null;
  CustomerType: string | null;
  Phone: string | null;
  hPhone: string | null;
  bPhone: string | null;
  cPhone: string | null;
  Email: string | null;
  Company: string | null;
  VehicleTypeId: number;
  VehicleType: string;
  ModelId: number | null;
  ModelName: null;
  CanceledDate: null;
  BasePrice: number;
  Note: string | null;
  AgreementId: number | null;
  AgreementNumber: string | null;
  CancellationCharge: null;
  AdvancedPayment: number;
  CreditCardExpiryDate: string | null;
  CreditCardNo: string | null;
  CreditCardType: string | null;
  CreditCardCVSNo: string | null;
  LDW: number;
  TLDW: number;
  SpecialNote: null;
  PromotionId: number;
  Deposit: number;
  LogId: number;
  CreditCardBillingZipCode: string | null;
  ImageName: string | null;
  TotalDays: number;
  IsCompound: boolean;
  FullDepositAmount: number;
  InstallmentAmount: number;
  PerInstallmentAmount: number;
  InstallmentQty: number;
  PreAdjustment: number;
  ReservationPrimaryId: number;
  Prep: boolean;
  Wrap: boolean;
  VehicleTypeId2: string | null;
  VehicleId2: string | null;
  VehicleMakeName2: string | null;
  ModelName2: string | null;
  Year2: number | null;
  LicenseNo2: string | null;
  VehicleNo2: string | null;
  VehicleType2: string | null;
  PONo: string | null;
  RONo: string | null;
  PONo2: string | null;
  RONo2: string | null;
  TotalDiscount: number;
  LocationId: number;
  DaysInWeek: number;
  CreatedBy: string | null;
  LastUpdateByName: string | null;
  ReservationStatus: number;
  IsRetrieval: false;
  IsDelivery: false;
  ProjectedMileage: null;
  ReferralId: null;
  VoucherNo: null;
  LocationEmail: string | null;
  LocationEmailName: string | null;
  ReferralCommission: number;
  Total: number;
  ReservationStatusName: string;
  CheckoutState: string | null;
  Checkinstate: string | null;
  Destination: string | null;
  RefferalName: string | null;
};
