export type VehicleListItemType = {
  id: string; // this is added in useGetVehiclesList.ts
  VehicleId: number;
  VehicleNo: string | null;
  ModelId: number;
  MakeId: number;
  VehicleMakeName: string | null;
  ModelName: string | null;
  Year: number;
  Active: boolean;
  LicenseNo: string | null;
  LicenseState: string | null;
  OwningLocationId: number;
  OwningLocationName: string | null;
  Color: string | null;
  CurrentLocationId: number;
  CurrentLocationName: string | null;
  StatusId: number;
  VehicleTypeId: number;
  VehicleType: string | null;
  CurrentOdometer: number;
  Transmission: string | null;
  Cylinders: number;
  Memo: string | null;
  FuelLevel: string;
  TankSize: number;
  CreatedBy: string;
  CreatedByName: string | null;
  LeasingCompanyName: string | null;
  InsuranceCompanyName: string | null;
  FuelType: string | null;
  LeaseAmt: number;
  DownPayment: number;
  CashValue: number;
  Vin: string | null;
  Replaced: boolean;
  VehicleStatus: string;
  VehicleImage: string | null;
  CurrentRenter: string | null;
  FutureRentalDate: string | null;
  LicenseStateName: string | null;
  IsUpgrade: boolean;
  Price: number | null;
  FullValue: number | null;
  Doors: string;
  Seats: number | null;
  Baggages: number;
};
