export interface ReservationsInList {
	ReserveId: number;
	AdditionalCharge: number;
	ReservationNumber: string;
	ReservationType: string | null;
	OwningLocationId: number | null;
	LowestRate: boolean | null;
	ClientId: number;
	CustomerId: number;
	VehicleId: number | null;
	VehicleMakeName: string | null;
	Trim: string | null;
	Year: number | null;
	StartDate: string;
	EndDate: string;
	CreatedDate: string;
	Notes: string | null;
	LicenseNo: string | null;
	VehicleNo: string | null;
	FuelType: string | null;
	FuelLevel: string | null;
	Transmission: string | null;
	CurrentOdometer: number | null;
	Color: string | null;
	Doors: number | null;
	Vin: string | null;
	StatusId: number;
	InsuranceAmt: number | null;
	StartLocationId: number;
	StartLocationName: string | null;
	StartLocationAddress1: string | null;
	StartLocationAddress2: string | null;
	StartLocationCity: string | null;
	StartLocationPhone: string | null;
	StartLocationCountryName: string | null;
	StartLocationStateName: string | null;
	EndLocationId: number;
	EndLocationName: string | null;
	FirstName: string | null;
	LastName: string | null;
	Address1: string | null;
	Address2: string | null;
	City: string | null;
	ProductionName: string | null;
	CountryName: string | null;
	ZipCode: string | null;
	DateOfBirth: string | null;
	CustomerType: string | null;
	Phone: string | null;
	hPhone: string | null;
	bPhone: string | null;
	cPhone: string | null;
	Email: string | null;
	Company: string | null;
	VehicleTypeId: number;
	VehicleType: string;
	ModelId: number;
	ModelName: string;
	CanceledDate: string | null;
	BasePrice: number;
	Note: string | null;
	AgreementId: number | null;
	AgreementNumber: string | null;
	CancellationCharge: number | null;
	AdvancedPayment: number;
	CreditCardExpiryDate: string | null;
	CreditCardNo: string | null;
	CreditCardType: string | null;
	CreditCardCVSNo: string | null;
	LDW: number;
	TLDW: number;
	SpecialNote: string | null;
	PromotionId: number;
	Deposit: number;
	LogId: number;
	CreditCardBillingZipCode: string | null;
	ImageName: string | null;
	TotalDays: number;
	IsCompound: boolean;
	FullDepositAmount: number;
	InstallmentAmount: number;
	PerInstallmentAmount: number;
	InstallmentQty: number;
	PreAdjustment: number;
	ReservationPrimaryId: number;
	Prep: boolean;
	Wrap: boolean;
	VehicleTypeId2: number | null;
	VehicleId2: number | null;
	VehicleMakeName2: string | null;
	ModelName2: string | null;
	Year2: number | null;
	LicenseNo2: string | null;
	VehicleNo2: string | null;
	VehicleType2: string | null;
	PONo: string | null;
	RONo: string | null;
	PONo2: string | null;
	RONo2: string | null;
	TotalDiscount: number;
	LocationId: number;
	DaysInWeek: number;
	CreatedBy: string | null;
	LastUpdateByName: string | null;
	ReservationStatus: number;
	IsRetrieval: boolean;
	IsDelivery: boolean;
	ProjectedMileage: number | null;
	ReferralId: number | null;
	VoucherNo: string | null;
	LocationEmail: string | null;
	LocationEmailName: null;
	ReferralCommission: number;
}
