export interface ReservationMiscViewDataFull {
	miscChargeId: number;
	miscChargeCode: number;
	unit: number;
	name: string;
	description: string;
	calculationType: "Fixed" | "Perday";
	taxNotAvailable: boolean;
	isCommission: boolean;
	value: number;
	totalValue: number;
	startDate: string;
	endDate: string;
	quantity: number;
	createdDate: string | null;
	gLcode: string | null;
	locationMiscChargeId: number;
	isChargeByPeriod: boolean;
	isTaxable: boolean;
	locationTaxIds: string | null;
	isSelected: boolean;
	isQuantity: boolean;
	locationMiscChargeID: number;
	vehicleTypeId: number;
	miscChargeID: number;
	misChargeCode: number;
	isOptional: boolean;
	printValue: number | null;
	oldStartDateString: string | null;
	oldEndDateString: string | null;
	startDateString: string | null;
	createddateString: string | null;
	endDateString: string | null;
	isDeleted: boolean;
	isFreeze: boolean;
	isAlreadySelected: boolean;
	isDeductible: boolean;
	locationId: number;
	locationName: string | null;
	vehicleType: number | null;
	miscTaxList: string | null;
	totaltax: number;
	subTotal: number;
	amountPaid: number | null;
	amountRemaining: number | null;
	miscchargeTypeId: number;
	option: number;
	misChargeOptionList: string | null;
	optionId: number | null;
}
export interface ReservationViewDataFull {
	reservationview: {
		reserveId: number;
		additionalCharge: number;
		reservationNumber: string | null;
		reservationType: string | null;
		owningLocationId: number;
		lowestRate: null;
		clientId: number;
		customerId: number;
		vehicleId: number;
		vehicleMakeName: string | null;
		trim: string | null;
		year: number;
		startDate: string;
		endDate: string;
		createdDate: string;
		notes: string | null;
		licenseNo: string | null;
		vehicleNo: string | null;
		fuelType: string | null;
		fuelLevel: string | null;
		transmission: string | null;
		currentOdometer: number;
		color: string | null;
		doors: number | null;
		vin: string | null;
		statusId: number;
		insuranceAmt: number | null;
		startLocationId: number;
		startLocationName: string | null;
		startLocationAddress1: string | null;
		startLocationAddress2: string | null;
		startLocationCity: string | null;
		startLocationPhone: string | null;
		startLocationCountryName: string | null;
		startLocationStateName: string | null;
		endLocationId: number;
		endLocationName: string | null;
		firstName: string | null;
		lastName: string | null;
		address1: string | null;
		address2: string | null;
		city: string | null;
		stateCode: string | null;
		productionName: string | null;
		countryName: string;
		zipCode: string | null;
		dateOfBirth: string | null;
		customerType: string | null;
		phone: string | null;
		hPhone: string | null;
		bPhone: string | null;
		cPhone: string | null;
		email: string | null;
		company: string | null;
		vehicleTypeId: number;
		vehicleType: string | null;
		modelId: number;
		modelName: string | null;
		canceledDate: string | null;
		basePrice: number;
		note: string | null;
		agreementId: number | null;
		agreementNumber: string | null;
		cancellationCharge: null;
		advancedPayment: number;
		creditCardExpiryDate: string | null;
		creditCardNo: string | null;
		creditCardType: string | null;
		creditCardCVSNo: string | null;
		ldw: number;
		tldw: number;
		specialNote: string | null;
		promotionId: number;
		deposit: number;
		logId: number;
		creditCardBillingZipCode: string | null;
		imageName: string | null;
		totalDays: number;
		isCompound: boolean;
		fullDepositAmount: number;
		installmentAmount: number;
		perInstallmentAmount: number;
		installmentQty: number;
		preAdjustment: number;
		reservationPrimaryId: number;
		prep: boolean;
		wrap: boolean;
		vehicleTypeId2: number | null;
		vehicleId2: number | null;
		vehicleMakeName2: string | null;
		modelName2: string | null;
		year2: number | null;
		licenseNo2: string | null;
		vehicleNo2: string | null;
		vehicleType2: string | null;
		poNo: string | null;
		roNo: string | null;
		poNo2: string | null;
		roNo2: string | null;
		totalDiscount: number;
		locationId: number;
		daysInWeek: number;
		createdBy: string | null;
		lastUpdateByName: string | null;
		reservationStatus: number;
		isRetrieval: boolean;
		isDelivery: boolean;
		projectedMileage: number | null;
		referralId: number | null;
		voucherNo: string | null;
		locationEmail: string | null;
		locationEmailName: string | null;
		referralCommission: number;
		total: number;
		totalRows: number;
		createdById: number;
		billingStartDate: string | null;
		billingEndDate: string | null;
		reservationStatusName: string;
		creditCardNoView: string | null;
		paymentMethodForAdvancepaymnts: string | null;
		paymentMethodForCancellationchrgs: string | null;
	};
	miscChargeList: ReservationMiscViewDataFull[];
	taxList: {
		taxId: number;
		name: string;
		description: string | null;
		value: number;
		isOption: boolean;
		isSelected: boolean;
		locationId: number;
		taxValue: number;
		locationName: string | null;
		locationTaxID: number;
		createdBy: number;
		createdByName: string | null;
		lastUpdatedByName: string | null;
		activeDate: string | null;
		expiryDate: string | null;
		activeDatestr: string | null;
		expiryDatestr: string | null;
		taxSelectedStatus: string | null;
		glCode: string | null;
	}[];
	rateList: ReservationRateList[];
	reservationTotal: number | null;
	reservationAttributeList: ReservationAttributeListItem[];
	paymentList: [];
	clientPdfTemplatesList: string[];
	emailTrackList: [];
	depositTotals: {
		depositAmount: number;
		onHoldAmount: number;
		refundAmount: number;
		releaseAmount: number;
		forfeitureAmount: number;
		totalCanceledAmount: number;
	};
	invoiceList: null;
	reservtionBillingReview: {
		billingInfoID: number;
		reservationID: number;
		contactName: string | null;
		contactAddress: string | null;
		contactPhone: string | null;
		contactEmail: string | null;
		isActive: boolean;
		billingBy: string;
		creditCardReferenceId: number | null;
		billingOwnerId: number;
	};
	reservationBillingList: ReservationBillingList[];
	mileageCharges: [];
	agreementReservationMileageBreakdown: [];
	navDynamicAttribute: null;
	agreementInsurance: null;
	customerImages: [];
	referral: string | null;
	driverList: ReservationDriverList[];
	customerDetails: {
		customerId: number;
		customerNumber: string | null;
		companyName: string | null;
		firstName: string | null;
		middleName: string | null;
		lastName: string | null;
		dateOfbirth: string | null;
		address1: string | null;
		address2: string | null;
		zipCode: string | null;
		city: string | null;
		stateId: number;
		countryId: number;
		hPhone: string | null;
		bPhone: string | null;
		cPhone: string | null;
		fax: string | null;
		licenseNumber: string | null;
		licenseCategory: string | null;
		email: string | null;
		hstNumber: string | null;
		active: boolean;
		countryName: string | null;
		stateName: string | null;
		stateCode: string | null;
		insuranceCompany: string | null;
		policyNumber: string | null;
		insuranceExpiryDate: string | null;
		insuranceCountry: string | null;
		insuranceProvince: string | null;
		creditCardType: string | null;
		creditCardNo: string | null;
		creditCardExpiryDate: string | null;
		creditCardCVSNo: string | null;
		insuranceState: string | null;
		billingAddress1: string | null;
		billingCity: string | null;
		billingZipCord: string | null;
		insuranceClaim: string | null;
		billStateName: string | null;
		billingStateId: number | null;
		billingCountyId: number | null;
		customerType: string | null;
		billCountryName: string | null;
		password: string | null;
		licenseIssueDate: string | null;
		licenseExpiryDate: string | null;
		licenseIssueState: string | null;
		passportNo: string | null;
		passportIssueDate: string | null;
		passportExpairyDate: string | null;
		locationId: number;
		locationName: string | null;
		creditCardBillingZipCode: string | null;
		rateName: string | null;
		productionName: string | null;
		nameOnCard: string | null;
		customerImage: string | null;
		drivingExperience: string | null;
		isBlackListed: boolean;
		blackListId: number;
		blackListDescription: string | null;
		blackListDate: string | null;
		blackListReason: number;
		licenseCountryId: string | null;
		accoutNameInBank: string | null;
		accountNumber: string | null;
		bsb: string | null;
		emergencyContactNo: string | null;
		companyRegNo: string | null;
		isSMSOpted: boolean;
		isEmailOpted: boolean;
		qboReferenceId: string | number | null;
		ticketFlag: number | null;
		clientId: number;
		createdBy: number | null;
		userName: string | null;
		totalRows: number;
		rowNum: number;
		paymentTerms: number;
		isTaxExempt: boolean;
		licenseCountryName: string | null;
		bankName: string | null;
		bankSwiftCode: string | null;
		createdByName: string | null;
		lastUpdatedBy: number | null;
		phone: string | null;
		lastUpdatedByName: string | null;
	};
}

interface ReservationAttributeListItem {
	keyValueId: number;
	reservationId: number;
	attributeId: number;
	value: string | null;
	groupId: number;
	groupName: string;
	keyValue: string;
	type: string;
	displayName: string | null;
}

interface ReservationDriverList {
	driverId: number;
	agreementId: number | null;
	customerId: number | null;
	driverName: string | null;
	firstName: string | null;
	lastName: string | null;
	dateOfBirth: string | null;
	driverType: number;
	createdBy: string | null;
	licenseNumber: string | null;
	licenseCategory: string | null;
	licenseExpiryDate: string | null;
	email: string | null;
	licenseIssueDate: string | null;
	licenseIssueState: string | null;
	hPhone: string | null;
	bPhone: string | null;
	cPhone: string | null;
	address: string | null;
	city: string | null;
	stateId: number;
	zipCode: string | null;
	countryId: number;
	signatureName: string;
	signatureImageUrl: string;
	reservationId: number;
	insuranceCompany: string | null;
	checkForDelete: number;
	dateofBirth: string | null;
	dateofBirthStr: string | null;
	createdDate: string | null;
	updatedDate: string | null;
	updateBy: string | null;
	driverLicenseNumber: string | null;
	driverLicenseCategory: string | null;
	driverLicenseExpiryDate: string | null;
	isDelete: boolean;
	isFromCustomer: boolean;
	phone: string;
	signatureImageUrlString: string | null;
	startDate: string | null;
	endDate: string | null;
	referenceType: string | null;
	referenceId: number | null;
	countryName: string | null;
}

interface ReservationRateList {
	clientId: number;
	locationId: number | null;
	rateId: number;
	vehicleTypeId: number | null;
	calculatedBy: string | null;
	kMorMileageCharge: number | null;
	fuelCharge: number | null;
	oneWayCharge: number | null;
	graceMinutes: null;
	hourlyRate: number;
	hourlyQty: number;
	halfDayRate: number;
	halfDayQty: number;
	dailyRate: number;
	dailyQty: number;
	weekendDayRate: number;
	weekendDailyQty: number;
	weeklyRate: number;
	weeklyQty: number;
	monthlyRate: number;
	monthlyQty: number;
	packageName: string | null;
	packageRate: number;
	packageRateId: number;
	totalDays: number;
	daysInWeek: number;
	extraHourlyRate: number | null;
	extraHourlyQty: number;
	extraDailyRate: number | null;
	extraDailyQty: number;
	extraWeekEndDayRate: number | null;
	extraWeekEndDayQty: number;
	extraWeeklyRate: number | null;
	extraWeeklyQty: number;
	dailyKMorMileageAllowed: number;
	weeklyKMorMileageAllowed: number;
	monthlyKMorMileageAllowed: number;
	totalKMorMileageAllowed: null;
	packageKMorMileageAllowed: number;
	packageDaysIncluded: number;
	lastUpdatedBy: string | null;
	lastUpdated: string | null;
	rateName: string | null;
	active: number | null;
	specialRate: number | null;
	specialKMorMileageAllowed: number | null;
	extraSpecialRate: number | null;
	startDate: string | null;
	endDate: string | null;
	startDateStr: string | null;
	endDateStr: string | null;
	rateValue: number;
	extraValue: number;
	howMany: number;
	howManyExtra: number;
	kmAllowed: number;
	isVisible: boolean;
	isLowest: boolean;
	rateTotal: number;
	extraRateTotal: number;
	userId: number;
	initalRate: number;
	incrementValue: number;
	dayRateList: number | null;
	estimatedTotal: number;
	taxSum: number;
	reservationSummary: number | null;
	initialCharge: number;
	initialChargeHours: number;
	halfHourlyRate: number | null;
	halfHourlyQty: number;
	actualHourlyRate: number | null;
	actualHalfDayRate: number | null;
	actualDailyRate: number | null;
	actualWeeklyRate: number | null;
	actualMonthlyRate: number | null;
	actualExtraHourlyRate: number | null;
	actualExtraDailyRate: number | null;
	actualExtraWeekllyRate: number | null;
}

interface ReservationBillingList {
	billingInfoID: number;
	reservationID: number;
	contactName: string | null;
	contactAddress: string | null;
	contactPhone: string | null;
	contactEmail: string | null;
	isActive: boolean;
	billingBy: string | null;
	creditCardReferenceId: number | null;
	billingOwnerId: number;
}
