// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as PublicRouteImport } from "./routes/_public.route"
import { Route as AuthRouteImport } from "./routes/_auth.route"
import { Route as AuthIndexImport } from "./routes/_auth/index"
import { Route as PublicOidcCallbackImport } from "./routes/_public/oidc-callback"
import { Route as PublicLogoutImport } from "./routes/_public/logout"
import { Route as AuthReservationsRouteImport } from "./routes/_auth/reservations/route"
import { Route as AuthReportsRouteImport } from "./routes/_auth/reports/route"
import { Route as AuthFleetRouteImport } from "./routes/_auth/fleet/route"
import { Route as AuthCustomersRouteImport } from "./routes/_auth/customers/route"
import { Route as AuthAgreementsRouteImport } from "./routes/_auth/agreements/route"
import { Route as AuthReportsIndexRouteImport } from "./routes/_auth/reports/index.route"
import { Route as AuthFleetIndexRouteImport } from "./routes/_auth/fleet/index.route"
import { Route as AuthCustomersIndexRouteImport } from "./routes/_auth/customers/index.route"
import { Route as AuthAgreementsIndexRouteImport } from "./routes/_auth/agreements/index.route"
import { Route as AuthSettingsDestinationRouteImport } from "./routes/_auth/settings_.$destination/route"
import { Route as AuthReservationsNewRouteImport } from "./routes/_auth/reservations_.new/route"
import { Route as AuthReservationsReservationIdRouteImport } from "./routes/_auth/reservations_.$reservationId/route"
import { Route as AuthFleetNewRouteImport } from "./routes/_auth/fleet/new.route"
import { Route as AuthCustomersNewRouteImport } from "./routes/_auth/customers/new.route"
import { Route as AuthAgreementsNewRouteImport } from "./routes/_auth/agreements/new.route"
import { Route as AuthReportsReportIdIndexRouteImport } from "./routes/_auth/reports/$reportId/index.route"
import { Route as AuthFleetVehicleIdIndexRouteImport } from "./routes/_auth/fleet/$vehicleId/index.route"
import { Route as AuthCustomersCustomerIdIndexRouteImport } from "./routes/_auth/customers/$customerId/index.route"
import { Route as AuthAgreementsAgreementIdIndexRouteImport } from "./routes/_auth/agreements/$agreementId/index.route"
import { Route as AuthReservationsReservationIdEditRouteImport } from "./routes/_auth/reservations_.$reservationId.edit/route"
import { Route as AuthFleetVehicleIdEditRouteImport } from "./routes/_auth/fleet/$vehicleId/edit.route"
import { Route as AuthCustomersCustomerIdEditRouteImport } from "./routes/_auth/customers/$customerId/edit.route"
import { Route as AuthAgreementsAgreementIdEditRouteImport } from "./routes/_auth/agreements/$agreementId/edit.route"
import { Route as AuthAgreementsAgreementIdCheckInRouteImport } from "./routes/_auth/agreements/$agreementId/check-in.route"

// Create Virtual Routes

const PublicLoggedOutLazyImport = createFileRoute("/_public/logged-out")()
const PublicDevLazyImport = createFileRoute("/_public/dev")()
const AuthSettingsIndexLazyImport = createFileRoute("/_auth/settings/")()

// Create/Update Routes

const PublicRouteRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import("./routes/_auth/index.lazy").then((d) => d.Route))

const PublicLoggedOutLazyRoute = PublicLoggedOutLazyImport.update({
  path: "/logged-out",
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() =>
  import("./routes/_public/logged-out.lazy").then((d) => d.Route),
)

const PublicDevLazyRoute = PublicDevLazyImport.update({
  path: "/dev",
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() => import("./routes/_public/dev.lazy").then((d) => d.Route))

const PublicOidcCallbackRoute = PublicOidcCallbackImport.update({
  path: "/oidc-callback",
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicLogoutRoute = PublicLogoutImport.update({
  path: "/logout",
  getParentRoute: () => PublicRouteRoute,
} as any)

const AuthReservationsRouteRoute = AuthReservationsRouteImport.update({
  path: "/reservations",
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/reservations/route.lazy").then((d) => d.Route),
)

const AuthReportsRouteRoute = AuthReportsRouteImport.update({
  path: "/reports",
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthFleetRouteRoute = AuthFleetRouteImport.update({
  path: "/fleet",
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthCustomersRouteRoute = AuthCustomersRouteImport.update({
  path: "/customers",
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthAgreementsRouteRoute = AuthAgreementsRouteImport.update({
  path: "/agreements",
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSettingsIndexLazyRoute = AuthSettingsIndexLazyImport.update({
  path: "/settings/",
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/settings/index.lazy").then((d) => d.Route),
)

const AuthReportsIndexRouteRoute = AuthReportsIndexRouteImport.update({
  path: "/",
  getParentRoute: () => AuthReportsRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/reports/index.route.lazy").then((d) => d.Route),
)

const AuthFleetIndexRouteRoute = AuthFleetIndexRouteImport.update({
  path: "/",
  getParentRoute: () => AuthFleetRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/fleet/index.route.lazy").then((d) => d.Route),
)

const AuthCustomersIndexRouteRoute = AuthCustomersIndexRouteImport.update({
  path: "/",
  getParentRoute: () => AuthCustomersRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/customers/index.route.lazy").then((d) => d.Route),
)

const AuthAgreementsIndexRouteRoute = AuthAgreementsIndexRouteImport.update({
  path: "/",
  getParentRoute: () => AuthAgreementsRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/agreements/index.route.lazy").then((d) => d.Route),
)

const AuthSettingsDestinationRouteRoute =
  AuthSettingsDestinationRouteImport.update({
    path: "/settings/$destination",
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/settings_.$destination/route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthReservationsNewRouteRoute = AuthReservationsNewRouteImport.update({
  path: "/reservations/new",
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/reservations_.new/route.lazy").then((d) => d.Route),
)

const AuthReservationsReservationIdRouteRoute =
  AuthReservationsReservationIdRouteImport.update({
    path: "/reservations/$reservationId",
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/reservations_.$reservationId/route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthFleetNewRouteRoute = AuthFleetNewRouteImport.update({
  path: "/new",
  getParentRoute: () => AuthFleetRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/fleet/new.route.lazy").then((d) => d.Route),
)

const AuthCustomersNewRouteRoute = AuthCustomersNewRouteImport.update({
  path: "/new",
  getParentRoute: () => AuthCustomersRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/customers/new.route.lazy").then((d) => d.Route),
)

const AuthAgreementsNewRouteRoute = AuthAgreementsNewRouteImport.update({
  path: "/new",
  getParentRoute: () => AuthAgreementsRouteRoute,
} as any).lazy(() =>
  import("./routes/_auth/agreements/new.route.lazy").then((d) => d.Route),
)

const AuthReportsReportIdIndexRouteRoute =
  AuthReportsReportIdIndexRouteImport.update({
    path: "/$reportId/",
    getParentRoute: () => AuthReportsRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/reports/$reportId/index.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthFleetVehicleIdIndexRouteRoute =
  AuthFleetVehicleIdIndexRouteImport.update({
    path: "/$vehicleId/",
    getParentRoute: () => AuthFleetRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/fleet/$vehicleId/index.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthCustomersCustomerIdIndexRouteRoute =
  AuthCustomersCustomerIdIndexRouteImport.update({
    path: "/$customerId/",
    getParentRoute: () => AuthCustomersRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/customers/$customerId/index.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthAgreementsAgreementIdIndexRouteRoute =
  AuthAgreementsAgreementIdIndexRouteImport.update({
    path: "/$agreementId/",
    getParentRoute: () => AuthAgreementsRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/agreements/$agreementId/index.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthReservationsReservationIdEditRouteRoute =
  AuthReservationsReservationIdEditRouteImport.update({
    path: "/edit",
    getParentRoute: () => AuthReservationsReservationIdRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/reservations_.$reservationId.edit/route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthFleetVehicleIdEditRouteRoute =
  AuthFleetVehicleIdEditRouteImport.update({
    path: "/$vehicleId/edit",
    getParentRoute: () => AuthFleetRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/fleet/$vehicleId/edit.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthCustomersCustomerIdEditRouteRoute =
  AuthCustomersCustomerIdEditRouteImport.update({
    path: "/$customerId/edit",
    getParentRoute: () => AuthCustomersRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/customers/$customerId/edit.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthAgreementsAgreementIdEditRouteRoute =
  AuthAgreementsAgreementIdEditRouteImport.update({
    path: "/$agreementId/edit",
    getParentRoute: () => AuthAgreementsRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/agreements/$agreementId/edit.route.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthAgreementsAgreementIdCheckInRouteRoute =
  AuthAgreementsAgreementIdCheckInRouteImport.update({
    path: "/$agreementId/check-in",
    getParentRoute: () => AuthAgreementsRouteRoute,
  } as any).lazy(() =>
    import("./routes/_auth/agreements/$agreementId/check-in.route.lazy").then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    "/_public": {
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    "/_auth/agreements": {
      preLoaderRoute: typeof AuthAgreementsRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/customers": {
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/fleet": {
      preLoaderRoute: typeof AuthFleetRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/reports": {
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/reservations": {
      preLoaderRoute: typeof AuthReservationsRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_public/logout": {
      preLoaderRoute: typeof PublicLogoutImport
      parentRoute: typeof PublicRouteImport
    }
    "/_public/oidc-callback": {
      preLoaderRoute: typeof PublicOidcCallbackImport
      parentRoute: typeof PublicRouteImport
    }
    "/_public/dev": {
      preLoaderRoute: typeof PublicDevLazyImport
      parentRoute: typeof PublicRouteImport
    }
    "/_public/logged-out": {
      preLoaderRoute: typeof PublicLoggedOutLazyImport
      parentRoute: typeof PublicRouteImport
    }
    "/_auth/": {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/agreements/new": {
      preLoaderRoute: typeof AuthAgreementsNewRouteImport
      parentRoute: typeof AuthAgreementsRouteImport
    }
    "/_auth/customers/new": {
      preLoaderRoute: typeof AuthCustomersNewRouteImport
      parentRoute: typeof AuthCustomersRouteImport
    }
    "/_auth/fleet/new": {
      preLoaderRoute: typeof AuthFleetNewRouteImport
      parentRoute: typeof AuthFleetRouteImport
    }
    "/_auth/reservations/$reservationId": {
      preLoaderRoute: typeof AuthReservationsReservationIdRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/reservations/new": {
      preLoaderRoute: typeof AuthReservationsNewRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/settings/$destination": {
      preLoaderRoute: typeof AuthSettingsDestinationRouteImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/agreements/": {
      preLoaderRoute: typeof AuthAgreementsIndexRouteImport
      parentRoute: typeof AuthAgreementsRouteImport
    }
    "/_auth/customers/": {
      preLoaderRoute: typeof AuthCustomersIndexRouteImport
      parentRoute: typeof AuthCustomersRouteImport
    }
    "/_auth/fleet/": {
      preLoaderRoute: typeof AuthFleetIndexRouteImport
      parentRoute: typeof AuthFleetRouteImport
    }
    "/_auth/reports/": {
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthReportsRouteImport
    }
    "/_auth/settings/": {
      preLoaderRoute: typeof AuthSettingsIndexLazyImport
      parentRoute: typeof AuthRouteImport
    }
    "/_auth/agreements/$agreementId/check-in": {
      preLoaderRoute: typeof AuthAgreementsAgreementIdCheckInRouteImport
      parentRoute: typeof AuthAgreementsRouteImport
    }
    "/_auth/agreements/$agreementId/edit": {
      preLoaderRoute: typeof AuthAgreementsAgreementIdEditRouteImport
      parentRoute: typeof AuthAgreementsRouteImport
    }
    "/_auth/customers/$customerId/edit": {
      preLoaderRoute: typeof AuthCustomersCustomerIdEditRouteImport
      parentRoute: typeof AuthCustomersRouteImport
    }
    "/_auth/fleet/$vehicleId/edit": {
      preLoaderRoute: typeof AuthFleetVehicleIdEditRouteImport
      parentRoute: typeof AuthFleetRouteImport
    }
    "/_auth/reservations/$reservationId/edit": {
      preLoaderRoute: typeof AuthReservationsReservationIdEditRouteImport
      parentRoute: typeof AuthReservationsReservationIdRouteImport
    }
    "/_auth/agreements/$agreementId/": {
      preLoaderRoute: typeof AuthAgreementsAgreementIdIndexRouteImport
      parentRoute: typeof AuthAgreementsRouteImport
    }
    "/_auth/customers/$customerId/": {
      preLoaderRoute: typeof AuthCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthCustomersRouteImport
    }
    "/_auth/fleet/$vehicleId/": {
      preLoaderRoute: typeof AuthFleetVehicleIdIndexRouteImport
      parentRoute: typeof AuthFleetRouteImport
    }
    "/_auth/reports/$reportId/": {
      preLoaderRoute: typeof AuthReportsReportIdIndexRouteImport
      parentRoute: typeof AuthReportsRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRouteRoute.addChildren([
    AuthAgreementsRouteRoute.addChildren([
      AuthAgreementsNewRouteRoute,
      AuthAgreementsIndexRouteRoute,
      AuthAgreementsAgreementIdCheckInRouteRoute,
      AuthAgreementsAgreementIdEditRouteRoute,
      AuthAgreementsAgreementIdIndexRouteRoute,
    ]),
    AuthCustomersRouteRoute.addChildren([
      AuthCustomersNewRouteRoute,
      AuthCustomersIndexRouteRoute,
      AuthCustomersCustomerIdEditRouteRoute,
      AuthCustomersCustomerIdIndexRouteRoute,
    ]),
    AuthFleetRouteRoute.addChildren([
      AuthFleetNewRouteRoute,
      AuthFleetIndexRouteRoute,
      AuthFleetVehicleIdEditRouteRoute,
      AuthFleetVehicleIdIndexRouteRoute,
    ]),
    AuthReportsRouteRoute.addChildren([
      AuthReportsIndexRouteRoute,
      AuthReportsReportIdIndexRouteRoute,
    ]),
    AuthReservationsRouteRoute,
    AuthIndexRoute,
    AuthReservationsReservationIdRouteRoute.addChildren([
      AuthReservationsReservationIdEditRouteRoute,
    ]),
    AuthReservationsNewRouteRoute,
    AuthSettingsDestinationRouteRoute,
    AuthSettingsIndexLazyRoute,
  ]),
  PublicRouteRoute.addChildren([
    PublicLogoutRoute,
    PublicOidcCallbackRoute,
    PublicDevLazyRoute,
    PublicLoggedOutLazyRoute,
  ]),
])
