import {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowDownLeftIcon,
  BanknoteIcon,
  BarChartIcon,
  BellIcon,
  CalendarIcon,
  CarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsDownUpIcon,
  CreditCardIcon,
  DollarSignIcon,
  DotIcon,
  EyeIcon,
  EyeOffIcon,
  FilesIcon,
  FileSignatureIcon,
  FolderIcon,
  GripVerticalIcon,
  LaptopIcon,
  LayoutDashboardIcon,
  Loader2Icon,
  LockIcon,
  LogOutIcon,
  MenuIcon,
  MoonIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  SearchIcon,
  SettingsIcon,
  SheetIcon,
  SortAscIcon,
  SortDescIcon,
  SunIcon,
  UnlockIcon,
  User2Icon,
  Users2Icon,
  XIcon,
  type LucideIcon as LucideIconType,
} from "lucide-react";

export type LucideIcon = LucideIconType;

export const icons = {
  Dot: DotIcon,
  X: XIcon,
  Loading: Loader2Icon,
  Alert: AlertCircleIcon,
  Warning: AlertTriangleIcon,
  ChevronsDownUp: ChevronsDownUpIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ArrowDownLeft: ArrowDownLeftIcon,
  Check: CheckIcon,
  Play: PlayIcon,
  Plus: PlusIcon,
  PlusCircle: PlusCircleIcon,
  EyeOn: EyeIcon,
  EyeOff: EyeOffIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Lock: LockIcon,
  System: LaptopIcon,
  Unlock: UnlockIcon,
  SortAsc: SortAscIcon,
  SortDesc: SortDescIcon,
  Menu: MenuIcon,
  Search: SearchIcon,
  Logout: LogOutIcon,
  Settings: SettingsIcon,
  DashboardLayout: LayoutDashboardIcon,
  BarChart: BarChartIcon,
  CreditCard: CreditCardIcon,
  Car: CarIcon,
  Calendar: CalendarIcon,
  Bell: BellIcon,
  Banknote: BanknoteIcon,
  DollarSign: DollarSignIcon,
  FileSignature: FileSignatureIcon,
  Files: FilesIcon,
  Folder: FolderIcon,
  GripVertical: GripVerticalIcon,
  Sheet: SheetIcon,
  User: User2Icon,
  Users: Users2Icon,
} as const;
